apiVersion: v1
kind: Service
metadata:
  name: payment-service
  labels:
    app: payment-service
spec:
  selector:
    app: payment-service
  ports:
    - prot: 80        # ❌ typo: should be 'port'
      targetPort: 8000
